openapi: 3.0.0
info:
  description: "API template"
  version: "0.0.0"
  title: "API template"
servers:
  - url: 'http://localhost:3000/'
paths:
  /users:
    get:
      tags:
        - "users"
      summary: "It should send an user but send only a message"
      responses:
        200:
          description: "User response"
  /resource:
    get:
      tags:
        - "resource"
      summary: "It should send an user but send only a message"
      responses:
        200:
          description: "User response"